// The strings the enrichment toggle needs on both surfaces it appears on — the add-site
// form (`components/landing/site-url-field.tsx`) and the detail page's
// `components/crawls/enrichment-panel.tsx` — mirroring `lib/crawls/schedule-presets.ts`: one
// module holding copy two components would otherwise have to keep in sync by hand.
//
// **No pricing constant in this file, or anywhere in the frontend (PER-194's own [Cost]
// acceptance criterion).** `ENRICHMENT_HELP` below states the MECHANISM and an
// order-of-magnitude, in prose, matching the backend's own help text
// (`backend/app/features/websites/schemas.py`'s `_ENRICH_WITH_LLM_DESCRIPTION`) — neither
// side computes a number from token counts or a price-per-token constant, because neither
// commits to a number that would drift the day a model's price changes.

/** The checkbox / toggle's own label, used on both surfaces. */
export const ENRICHMENT_LABEL = "Summarize pages with Claude";

/**
 * The help text under the toggle.
 *
 * **Leads with the effect on the artifact, then the cost.** The earlier wording opened on the
 * mechanism and the price and never said what the setting actually changes, which left the
 * reader to guess whether summaries land in their llms.txt or somewhere else entirely. What
 * enrichment does is narrow and worth stating plainly: it rewrites each entry's title and
 * description — and nothing else about the crawl — so naming those two fields is both the
 * clearest description and an accurate one.
 *
 * Still states the mechanism and an order of magnitude rather than a computed estimate, so a
 * change to actual pricing never makes this sentence wrong. Mirrors
 * `backend/app/core/settings.py`'s own arithmetic comment for `crawl_enrich_max_chars`.
 */
export const ENRICHMENT_HELP =
  "Claude writes the titles and descriptions in your llms.txt instead of reusing each page's own. One Claude Haiku 4.5 call per page, on the first 4,000 characters — cents for a 100-page run.";

/** The Runs-tab and Output-tab badge's visible text, when a run asked for enrichment and did
 * not get it — `lib/crawls/run-display.ts`'s `runEnrichmentFellBack` is the predicate that
 * decides when this shows at all. */
export const ENRICHMENT_FALLBACK_BADGE = "Enrichment unavailable";

/** The tooltip attached to the badge above — the full sentence, since the badge itself has to
 * stay short enough to sit beside `RunStatusIndicator` in a table cell. */
export const ENRICHMENT_FALLBACK_EXPLANATION =
  "Enrichment requested but unavailable — titles come from the page.";

/**
 * The `/crawls` Schedule cell's enrichment indicator (`components/crawls/crawl-schedule.tsx`)
 * — **future tense**, on purpose. `websites.enrich_with_llm` is intent for the *next* run, not
 * a fact about any run that has already happened, so this string has to read as a forecast
 * rather than a status. It deliberately does not reuse `ENRICHMENT_LABEL` ("Summarize pages
 * with Claude") — that is the checkbox's own label, worded as an instruction to the toggle
 * itself, not as a sentence describing what a table cell means.
 *
 * **Rendered `sr-only`, not visibly.** At the 13% `columns.ts` gives the Schedule column this
 * text alongside an interval badge wrapped to a second line, making the row taller than the
 * shared `ROW_HEIGHT`; the cell shows the wand icon alone and uses this string as the
 * accessible name instead (see `EnrichmentForecastBadge` in crawl-schedule.tsx, and that
 * cell's docstring for why it still renders with no schedule at all). Keep it a label naming
 * the thing itself, not a sentence — a screen reader announces it as the badge's name.
 */
export const ENRICHMENT_NEXT_RUN_BADGE = "Enriches next run";

/** The tooltip attached to the badge above, spelling out the forecast the short label above
 * only gestures at. */
export const ENRICHMENT_NEXT_RUN_EXPLANATION =
  "This site's next run will summarize its pages with Claude.";

/**
 * The Runs-tab and Output-tab badge's visible text when a run's stats say enrichment actually
 * ran — **past tense**, and deliberately not a rewording of the badge above. `/crawls`
 * answers "is this on, and what happens next"; this answers "did this particular run get it".
 * A user who just flipped the toggle on sees the site marked with the future-tense badge while
 * every run before that moment still shows nothing (`runEnrichmentState` returns `null` for a
 * run whose `stats` carry no enrichment keys at all — see that function's own docstring for why
 * `undefined` is never read as `false`) — two different sentences is what keeps that gap
 * reading as history rather than as a bug once this run — the first enriched one — appears.
 */
export const ENRICHMENT_APPLIED_BADGE = "Enriched with Claude";

/** The tooltip attached to the badge above. */
export const ENRICHMENT_APPLIED_EXPLANATION =
  "This run's titles and descriptions were generated by Claude.";

/**
 * The Trends tab's "Titles & descriptions" tile/column copy when `metadata_changed` is `null`
 * — keyed by `RunIndexDiff.metadata_not_comparable_reason`
 * (`backend/app/features/runs/schemas.py`). Two entries, not one: the direction the toggle
 * flipped changes which sentence is true, and rendering the ticket's own sentence verbatim
 * for the case it describes (and its mirror for the other) is more honest than one sentence
 * that tries to cover both directions at once.
 */
export const METADATA_NOT_COMPARABLE: Record<"enrichment_enabled" | "enrichment_disabled", string> =
  {
    enrichment_enabled:
      "Enrichment turned on since the last comparison — titles and descriptions aren't comparable this run.",
    enrichment_disabled:
      "Enrichment turned off since the last comparison — titles and descriptions aren't comparable this run.",
  };
